profile=gpu-next
hwdec=auto-safe
ytdl-format=bestvideo+bestaudio/best

icc-profile-auto=yes

dither=fruit
temporal-dither=yes

tone-mapping=spline
hdr-compute-peak=yes

deband=no
deband-iterations=4
deband-threshold=32
deband-range=20
deband-grain=6

glsl-shader="~~/shaders/KrigBilateral.glsl"
glsl-shader="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"

scale=ewa_lanczossharp
dscale=mitchell

sigmoid-upscaling=yes
correct-downscaling=yes
linear-downscaling=yes

video-sync=display-resample
interpolation=no