# Core and Hardware
profile=gpu-hq
hwdec=auto-safe
ytdl-format=bestvideo+bestaudio/best

# Scaling and AI
glsl-shader="~~/shaders/KrigBilateral.glsl"
glsl-shader="~~/shaders/FSRCNNX_x2_16-0-4-1.glsl"
scale=ewa_lanczossharp
dscale=mitchell

# Smoothness and Synchronization
video-sync=display-resample
interpolation=yes
tscale=oversample