profile=high-quality
vo=gpu-next
hwdec=auto-safe
ytdl-format=bestvideo+bestaudio/best

ao=pipewire
gapless-audio=yes

audio-resample-filter-size=32
audio-resample-cutoff=0.99
audio-resample-linear=yes

icc-profile-auto=yes

temporal-dither=yes

tone-mapping=spline
hdr-compute-peak=yes

deband=no
deband-iterations=4
deband-threshold=32
deband-range=20
deband-grain=6

glsl-shader="~~/shaders/KrigBilateral.glsl"
glsl-shader="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"

dscale=mitchell

video-sync=display-resample

[audio]
profile-cond=audio and (not video or (current_tracks and current_tracks['video'] and current_tracks['video']['albumart']))
profile-restore=copy
force-window=no
audio-display=embedded-first
autofit=500x500
geometry=50%:50%
glsl-shaders-clr