# Temel ve Donanım
profile=gpu-hq
hwdec=auto-safe
ytdl-format=bestvideo+bestaudio/best

# Ölçeklendirme ve Yapay Zeka
glsl-shaders="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell

# Akıcılık ve Senkronizasyon
video-sync=display-resample
interpolation
tscale=oversample